name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print-Greeting
        run: echo "say hello!"
      - name: Say-Goodbye
        run: echo "Good Bye"
